### ISSUE TITLE
Vine support

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/film_snob#1]
PRO TIP: For vine support need use `noembed` service and `http://noembed.com/embed` link.

**Comment by maxjacobson** [comment]
I don't want to depend on an external service. I'd rather look at how they implemented it (https://github.com/leedo/noembed/blob/master/lib/Noembed/Provider/Vine.pm) and see if we can learn from it

**Comment by davydovanton** [comment]
@maxjacobson what you think if i add any russian video serves? like as [rutube](http://rutube.ru/)?

**Comment by maxjacobson** [comment]
I say: why not? Sounds cool
